Update the A/B installer code for A/B devices with a recovery partition

diff --git a/installer/META-INF/com/google/android/update-binary b/installer/META-INF/com/google/android/update-binary
--- a/installer/META-INF/com/google/android/update-binary
+++ b/installer/META-INF/com/google/android/update-binary
@@ -45,7 +45,7 @@ OF_VANILLA_BUILD=0
 FOX_R11=0
 
 # last_modified
-MOD_DATE="20201026"
+MOD_DATE="20201201"
   
 # sundry glodal defaults
 # VEND_DIR="/vendor"
@@ -230,9 +230,21 @@ is_SAR() {
   local F=$($GETPROP "ro.build.system_root_image")
   [ "$F" = "true" ] && {
     echo "1"
-    return  
+    return
   }
 
+  F=$($GETPROP "ro.boot.dynamic_partitions")
+  [ "$F" = "true" ] && {
+    echo "1"
+    return
+  }
+
+  F=$($GETPROP "ro.orangefox.sar")
+  [ "$F" = "1" ] && {
+    echo "1"
+    return
+  }
+  
   F=$(grep -s "/system_root" "/etc/fstab")
   [ -n "$F" ] && {
      echo "1"
@@ -249,7 +261,7 @@ is_SAR() {
      echo "1"
      return
   }
-  
+
   F=$($GETPROP ro.twrp.sar)
   [ "$F" = "true" ] && echo "1" || echo "0"
 }
@@ -431,30 +443,68 @@ Unzip_Installer_Package() {
 }
 
 # routine for flashing on A/B devices (credits: osm0sis)
+# argument: "0" (if there is no recovery partition); or recovery partition size (if there is one)
 AB_Install_Recovery() {
+local part_size="$1"
 local tool="$EX_DIR"/magiskboot
 local target="$EX_DIR"/boot.img
 local slot
 local name
+local PART
 
    	cd "$EX_DIR"
-   	chmod 0755 "$tool"
+   	
+   	if [ ! -f "$tool" ]; then
+   	   tool=$(which magiskboot)
+   	   [ -z "$tool" ] && abort "- I cannot find magiskboot. Quitting!"
+   	fi
 
-   	# extract the ramdisk from the OrangeFox image
-   	ui_print "- Extracting the OrangeFox ramdisk ..."
-   	"$tool" unpack recovery.img || abort "- I cannot extract the OrangeFox ramdisk. Quitting!"
-   	rm -f kernel dtb kernel_dtb
-   	cp -f ramdisk.cpio ramdisk-ofrp.cpio
-   	rm -f ramdisk.cpio
+   	if [ ! -f "recovery.img" ]; then
+   	   abort "- I cannot find the OrangeFox recovery image. Quitting!"
+   	fi
 
 	# target partition without the slot suffix
-	if [ -e /dev/block/bootdevice/by-name/recovery_b ]; then
-		target=/dev/block/bootdevice/by-name/recovery
+	[ -z "$part_size" ] && part_size="0"
+	if [ -e /dev/block/bootdevice/by-name/recovery_b -a "$part_size" != "0" ]; then
+	    target="/dev/block/bootdevice/by-name/recovery"
+	    name="recovery"
 	else
-		target=/dev/block/bootdevice/by-name/boot
+	    ui_print "- Standard A/B device ..."
+	    target="/dev/block/bootdevice/by-name/boot"
+	    name="boot"
 	fi
-	name=$(basename $target)
 
+	# if we have a recovery  partition - install the recovery image to recovery _a /_b
+	if [ "$name" = "recovery" ]; then
+	   ui_print "- A/B device - a recovery partition exists"
+	   # check against partition size - again
+	   local rec_size=$(FileSize "recovery.img")
+	   [ $rec_size -gt $part_size ] && abort "The recovery image ($rec_size bytes) is bigger than your recovery partition ($part_size bytes)! Quitting."
+	   # if we get here, it is safe to flash the image to the recovery _a /_b slots
+	   tmp=$($GETPROP "ro.boot.slot_suffix")
+	   ui_print "- The active slot is $tmp ..."
+	   for slot in _a _b; do
+		ui_print "- Installing OrangeFox to slot $slot..."
+		PART=$target"$slot"
+		blockdev --setrw $PART
+		package_extract_file "recovery.img" "$PART"
+	   done
+	   return
+	fi
+
+   	# extract the ramdisk from the OrangeFox image
+   	chmod 0755 "$tool"
+   	ui_print "- Extracting the OrangeFox ramdisk ..."
+   	"$tool" unpack recovery.img || abort "- I cannot extract the OrangeFox ramdisk. Quitting!"
+
+	# deal with ramdisk cpio
+   	if [ ! -f "ramdisk.cpio" ]; then
+   	   abort "- Error extracting the OrangeFox ramdisk. Quitting!"
+   	fi
+   	cp -f ramdisk.cpio ramdisk-ofrp.cpio
+   	rm -f ramdisk.cpio
+   	rm -f kernel dtb kernel_dtb
+	
 	# deal with both slots
 	for slot in _a _b; do
 		ui_print "- Running boot image patcher on slot $name$slot..."
@@ -475,6 +525,7 @@ local name
 		cp -f ramdisk-ofrp.cpio ramdisk.cpio
 		"$tool" repack boot.img || abort "- I cannot repack the $name$slot image!"
 
+		blockdev --setrw $target$slot
 		cat new-boot.img /dev/zero > $target$slot 2>/dev/null || true
 		rm -f boot.img dtb kernel new-boot.img ramdisk.cpio header
 		"$tool" cleanup
@@ -495,6 +546,7 @@ local name
 FileSize() {
   if [ -f $1 ]; then
      set -- $(ls -l "$1"); echo "$5"
+     # stat -c %s "$1"
   else
      echo "0"
   fi
@@ -512,26 +564,40 @@ local Is_ABD="0"
     [ "$OF_AB_DEVICE" = "1" -o "$(Is_AB_Device)" = "1" ] && Is_ABD="1"
     [ "$Is_ABD" = "1" ] && {
        ui_print "- The device is an A/B device."
+       # verify that there is no recovery partition
        [ -z "$ttmp" ] && {
-          AB_Install_Recovery
+          AB_Install_Recovery "0"
           return
        }
        # if we get here, it is A/B, but it has a recovery partition!
        ui_print "- But it also has a recovery partition!"
     }
 
+    # get the size of the recovery partition
     local bak="/tmp/org_recovery.img"
-    dd if="$PART" of=$bak > /dev/null 2>&1
+    dd bs=1048576 if="$PART" of=$bak > /dev/null 2>&1
     local oldF=$(FileSize $bak)
     local newF=$(FileSize recovery.img)
     ui_print "- Partition_Size=$oldF bytes; Recovery_Size=$newF bytes"
-    [  $newF -gt $oldF ] && {
+    [ $newF -gt $oldF ] && {
        rm -f $bak
        [ "$Is_ABD" = "1" -a "$oldF" = "0" ] && {
-          ui_print "- Hmmm ... an A/B device with a zero byte recovery partition!"
-          ui_print "- Resorting to the A/B installation procedure..."
-          AB_Install_Recovery
-          return
+          PART=$PART"_a"
+          dd bs=1048576 if="$PART" of=$bak > /dev/null 2>&1
+          oldF=$(FileSize $bak)
+          rm -f $bak
+          if [ "$oldF" = "0" ]; then
+             ui_print "- Hmmm ... an A/B device with a zero byte recovery partition!"
+             ui_print "- Resorting to the A/B installation procedure..."
+             AB_Install_Recovery "0"
+             return
+          else
+             ui_print "- Recovery parition exists! Using the A/B installation procedure..."
+             ui_print "- Partition_Size=$oldF bytes; Recovery_Size=$newF bytes"
+             [ $newF -gt $oldF ] && abort "The recovery image ($newF bytes) is bigger than your recovery partition ($oldF bytes)! Quitting."
+             AB_Install_Recovery "$oldF"
+             return
+          fi
        }
        abort "The recovery image ($newF bytes) is bigger than your recovery partition ($oldF bytes)! Quitting."
     }
